### ISSUE TITLE
Serial commas

### ISSUE THREAD

**Issue by phips** [StyleGuides/WritingStyleGuide#145]
I notice our guiding light is the AP Stylebook, which [does not advocate the serial comma](https://en.wikipedia.org/wiki/Serial_comma#Mainly_American_style_guides_opposing_typical_use) in simple lists.

But here in this style guide [we go against that](https://github.com/StyleGuides/WritingStyleGuide/blob/8f3fae1d6dac61f892d6c66202661c57cea29fde/en-US/Punctuation.xml#L365).

Should we update this style guide to reflect the AP Stylebook for consistency?

**Comment by daobrien** [comment]
Actually our guiding light is The IBM Style Guide, not AP. The RH Corporate Style Guide, aimed at corporate comms, Marketing, etc., uses AP. The RH Tech Writing Style Guide is used for technical writing projects.

Closing as NOTABUG.

**Comment by phips** [comment]
Given our future I guess that makes sense :) Thanks for fast comment @daobrien
