### ISSUE TITLE
Elaborate section on lists.

### ISSUE THREAD

**Issue by daobrien** [StyleGuides/WritingStyleGuide#159]
The following discussion is ongoing, and waiting for a suitable location in the Style Guide.

Note that the examples here refer to "standard" DocBook lists and lists with the `spacing="compact"` attribute. If you are writing in a different source language, use whichever attributes are appropriate.

I've heard quite a few ppl comment about saving space and reducing the page count of PDF files. The flip side is if clarity and readability suffer when we use compact lists then we're just shooting ourselves in the foot. I can tell you right now we go overboard with graphics in many cases so saving page count can't be that important. Clarity comes first.

In the original example, the list entries were nearly all single words. In these cases we don't need the white space to help clarity. If, on the other hand, some entries consisted of >=2 complete lines then I'd be more inclined to use a standard list. I think this would be especially true for 3+ entries. In a compact list, that would start to look like a very long and dense paragraph within which it would be easy to get lost.

Summary:
Use a standard `<itemizedlist>` if the content includes:
- Nested lists.
- Graphics (this should be strongly discouraged).
- Contain navigation or similar instructions (Navigate to Menu -> Submenu).
- Wrap to two or more lines.

Use a compact list in all other cases.

**Comment by daobrien** [comment]
@nmuller66 Can you add your 2€ worth?

**Comment by daobrien** [comment]
Example of the render of the two different list types in PDF:

![list-compact](https://user-images.githubusercontent.com/1518237/73332329-20324a00-42b2-11ea-8ac6-41db332b9495.png)
![list-normal](https://user-images.githubusercontent.com/1518237/73332330-20cae080-42b2-11ea-9311-de7c5c714b19.png)

**Comment by nmuller66** [comment]
- Concur that for single line list entries, lists should include the `spacing="compact"` attribute. 
- I am unsure that using a nested list should require a standard `<itemizedlist>` if otherwise the list conforms to the standards above. Can you clarify your thinking?
- Agree that graphics should not appear in lists. FWIW, I would probably outlaw them, rather than strongly discouraging. If you need a graphic, then `<itemizedlist>` is the wrong choice for organizing the content. Of course, there are likely to be edge cases that will arise as soon as we  state an absolute. 
- Agree that the other items (the bullet wraps to a subsequent line or lines; contains instructions) are best rendered as a standard `<itemizedlist>` for clarity and ease of consumption.

**Comment by daobrien** [comment]
A few different options to consider. We might need to include a "Use your discretion" clause because not all lists are created equal.

-----
![list-standard-nest](https://user-images.githubusercontent.com/1518237/73413316-0139c380-4357-11ea-9e3b-9cba906afe1f.png)

-----
![list-compact-nest](https://user-images.githubusercontent.com/1518237/73413317-01d25a00-4357-11ea-91ad-93ba09da4f13.png)

-----
![list-standard-parent-and-nest](https://user-images.githubusercontent.com/1518237/73413807-896c9880-4358-11ea-9626-5717f8209c3e.png)


Personally I think having the parent and nest set to `compact` makes the list a bit busy (example 2). Having the parent set to `standard` and the nest set to `compact` looks ok in this example (example 1). The last example, using `standard` for both parent and nest, does seem to use extra space for no apparent gain.

**Comment by daobrien** [comment]
@nmuller66 
>   Agree that graphics should not appear in lists. FWIW, I would probably outlaw them,
rather than strongly discouraging. If you need a graphic, then `<itemizedlist>` is the wrong 
choice for organizing the content. Of course, there are likely to be edge cases that will arise 
as soon as we  state an absolute.

How do you feel about `<screen>` elements in lists? This happens quite a lot. In procedures it's expected - we'd be lost without it - but what about bulleted lists? We use these in narrative and might be difficult to avoid.

-----
![list-standard-with-screens](https://user-images.githubusercontent.com/1518237/73452433-9ff50d00-43b5-11ea-97e4-01c10d123e76.png)

**Comment by nmuller66** [comment]
I agree that screen elements are needed, and for some reason less objectionable to fickle me. I wasn't considering them as "graphics." I may have overstated my objections, as graphics might sometimes be needed, but having large graphics or screen shots in a list always looks a bit wonky to me.

Agree that `compact` list nested in `compact` list looks squished, but the `standard` list nested in standard list wastes a good deal of space. A user discretion cause makes sense as there will inevitably exceptions.

**Comment by daobrien** [comment]
Done and published.

**Comment by daobrien** [comment]
Not sure what's happened but this doesn't appear in the public guide. Need to review.

**Comment by daobrien** [comment]
Fixed and scheduled for release.
