### ISSUE TITLE
Writing Style Guide for Technical Docs at Red Hat

### ISSUE THREAD

**Issue by ncbaratta** [StyleGuides/WritingStyleGuide#160]
In: https://github.com/StyleGuides/WritingStyleGuide/blob/dev/README.md#writingstyleguide it mentions a Style Guide that isn't used by technical documentation writers at Red Hat.  We actually use the IBM Style Guide when writing technical documentation.

**Comment by daobrien** [comment]
Quite a few groups in RH use the IBM guide, and some also use https://stylepedia.net/style as an adjunct to that. Different groups use different combinations of guides; e.g., Marketing and Brand use the Corporate Style Guide in combination with AP.
