### ISSUE TITLE
Fix entry for "Futexes" to align with revised entry for "mutex"

### ISSUE THREAD

**Issue by daobrien** [StyleGuides/WritingStyleGuide#166]

**Comment by nmuller66** [comment]
These entries appear to be identical:

Futexes
    Correct. "Futex" is an abbreviation of "fast user-space mutex." Consequently, "futexes" is the correct plural form. 
Mutexes
    Correct. "Mutex" is an abbreviation of "mutual exclusion." Consequently, "mutexes" is the correct plural form. 

@daobrien - can you clarify the description when you have a chance?

**Comment by daobrien** [comment]
Looks like it already got fixed but the big didn't get closed :confused:
