### ISSUE TITLE
Clarity on 'admin user'

### ISSUE THREAD

**Issue by niklucas** [StyleGuides/WritingStyleGuide#168]
Standardization on how to refer to admin user, administrative user, etc.

**Comment by rmahroua** [comment]
To follow up on what Phil was suggesting:

- Be as explicit as possible when referring to an administrative user. In many products, there's a default user that has administrative privileges, but it not necessarily named `admin`. Such is the case for the `kubeadmin` user in Kubernetes/OpenShift.
- Moreover, in many products, only the RBAC model dictates what constitutes an administrative user. In courses such as DO425, we create many regular users that we promote to admin. by giving them the proper RBAC (role) bindings.
- The idea would be to refer to the user as follows:

```
Connect as the `admin` user, who has administrative privileges
```

Or

```
Log in to X with `lisa`, who has administrative access
```
If working with that user is the focal point of an activity, then there is no need to repeat the fact that the user has administrative privileges:
- Log back in as `lisa`

This would help reinforce who is the user that has an administrative privileges and make the students aware of that.

**Comment by daobrien** [comment]
Ack'd and merged to devel.
