### ISSUE TITLE
Add entry for "once"

### ISSUE THREAD

**Issue by daobrien** [StyleGuides/WritingStyleGuide#172]
This appears not to be called out specifically anywhere.

We need to explain that in RH docs "once" means "one time"; that is, it is only used in a temporal sense. Don't write (e.g.) "Once you have download the software..."

The guide actually contains some of this incorrect use and we need to fix it.

**Comment by daobrien** [comment]
@nmuller66 @sffrench I hope I'm not overloading you :)

**Comment by sffrench** [comment]
I have addressed this in https://github.com/StyleGuides/WritingStyleGuide/pull/182. It is my first time doing this so please let me know if there are any more steps to the process I may have missed.
