### ISSUE TITLE
Add information on verbiage for recommendations

### ISSUE THREAD

**Issue by daobrien** [StyleGuides/WritingStyleGuide#173]
Need clarification on permitted verbiage for recommendations. Here a couple of examples of how this is often written (using "It is recommended...")

"Although the attack surface is reduced to the same-project traffic, it is recommended to create multiple service accounts within a project."
"It is recommended to generate a service account for each microservice in your project."
I edited this text to read "Red Hat recommends..." but concerns were expressed by the author and ID regarding whether this opens us to liability.

Because this is simply a recommendation and not a guarantee, there should be no liability issue. Per David O'Brien, this was previously discussed and the "Red Hat recommends..." verbiage accepted. However, this hasn't been specifically documented. David has contacted Legal to make sure.

The Red Hat Style Guide also indicates that "recommended practice" is a good substitution for "best practice" but the issue of how and when we make recommendations is not addressed.

We need to clarify and offer some options. The following rewrites of the above examples are acceptable:

Example 1

"Although the attack surface is reduced to the same-project traffic, Red Hat recommends creating multiple service accounts within a project."

Example 2

"Red Hat recommends that you generate a service account for each microservice in your project."

I think the verbiage "Red Hat recommends is preferable and more direct." Since we (Red Hat) are writing the content, it seems implied that the recommendation comes from Red Hat.

**Comment by daobrien** [comment]
@nmuller66 Transferred from the DocBook Guide repo. Have ack from Legal to continue.

**Comment by nmuller66** [comment]
Thanks @daobrien - Should I remove this from the DocBook Guide repo?

**Comment by daobrien** [comment]
Yes, I meant to do that but I think I was asleep at the time :) Thanks

**Comment by nmuller66** [comment]
I've made an update but waiting to push and create a PR until I can view/render. Sent a message to @daobrien for assistance.

**Comment by daobrien** [comment]
Fixed by #190
