### ISSUE TITLE
Using ssh/SSH in documentation

### ISSUE THREAD

**Issue by nmuller66** [StyleGuides/WritingStyleGuide#179]
For reference, please refer to the following:

https://stylepedia.net/style/#s

⁠SSH
Initialism for Secure Shell, a network protocol that allows data exchange using a secure channel. When referring to the protocol, do not use "ssh," "Ssh," or other variants. When referring to the command, use ssh. 
**Do not use as a verb**. For example, instead of "ssh to the remote server," write "Use SSH to connect to the remote server,"
"Open an SSH connection," or something similar.

This contains an especially important piece of information, and it took me a good five minutes to find it: "Do not use as a verb."

Information should be easier than that to find.

**Comment by nmuller66** [comment]
Nicole starting work on this 6/25/20

**Comment by nmuller66** [comment]
Changes in PR: https://github.com/StyleGuides/WritingStyleGuide/pull/189

**Comment by daobrien** [comment]
Fixed by #189
