### ISSUE TITLE
Use "navigate" to describe moving through multiple GUI options

### ISSUE THREAD

**Issue by nmuller66** [StyleGuides/WritingStyleGuide#188]
Use "Navigate to" in these scenarios of moving through multiple GUI options because it covers all cases where you might have to click, point to, select, or otherwise make a series of selections to initiate an action.
Example:
"From the OpenShift web console, navigate to Monitoring → Alerting." 

Created a related issue to update examples in the GLS DocBook Guide (https://stylepedia.net/docbook/index.html#gui-menu) to reflect this decision (https://github.com/RedHatTraining/xml-tagging-guide/issues/136).

**Comment by daobrien** [comment]
We need to push this one up the list and get it done sooner rather than later.

**Comment by nmuller66** [comment]
I will get to this as soon as I can. The DO328 and DO380 releases are imminent, and I am OOO on 7/22-23 but can possibly pick it up on 7/24; @sffrench if you find yourself with time on your hands this week, this might be something useful to pick up.

**Comment by sffrench** [comment]
Hey @nmuller66 and @daobrien. I had some free time to tackle this and I used your wording Nicole. PR up for it now https://github.com/StyleGuides/WritingStyleGuide/pull/198

**Comment by daobrien** [comment]
Scheduled for publication.
