### ISSUE TITLE
Track inclusive language issues

### ISSUE THREAD

**Issue by daobrien** [StyleGuides/WritingStyleGuide#191]
We need to keep track of the outcomes from the Conscious Language working group and update the guide accordingly.
This means both adding terms and phrases that we need to avoid, offer alternatives, and so on, and also reviewing the guide itself for any such language. e.g.
- [ ] master and slave
- [ ] blacklist
- [ ] whitelist
- [ ] 100's more...

**Comment by daobrien** [comment]
@nmuller66 Because you have the #wordsmatter gurnsey I'm taking the liberty of assigning this to you :)

**Comment by daobrien** [comment]
@julian-cable @nmuller66 Can you guys work on this together or volunteer yourself to take over... whatever works? Be good to reduce the number of duplicates and overlaps we have, too. Thanks

**Comment by julian-cable** [comment]
Yes, agreed! I'm already in the loop with the Conscious Language working group and have added a section about inclusive language to the style guide, with their agreement.

**Comment by julian-cable** [comment]
Closing the issue for now. Ongoing collaboration with Conscious Language working group; will add further material to the style guide as needed.
