### ISSUE TITLE
Review entry for life cycle

### ISSUE THREAD

**Issue by alexpdp7** [StyleGuides/WritingStyleGuide#224]
https://github.com/StyleGuides/WritingStyleGuide/blob/dev/en-US/L.xml#L104

We use two words "life cycle" and refer to the IBM word usage guide, which apparently has been updated underneath us to "lifecycle". I would suggest we remove the reference to the IBM guide (if we wish to keep our spelling) or remove the entry (if we wish to defer to IBM).

**Comment by dkolepp** [comment]
... and create a "vale" rule for this, because it's hard to keep track of
this ... :D

**Comment by daobrien** [comment]
> ... and create a "vale" rule for this, because it's hard to keep track of this ... :D
> […](#)
What are you basing Vale rules on? I.e., are you creating them independently or somehow linking them to the style guide? Which part is hard to keep track of?

**Comment by alexpdp7** [comment]
If you want to look at some rules we're using now, you can peek at:

https://github.com/RedHatTraining/DO250/tree/main/styles

We tend to provide a message that links to a source, like in:

https://github.com/RedHatTraining/DO250/blob/main/styles/GlsWordUsage/can.yml

, but we are certainly not 100% diligent on doing that and we should improve.

**Comment by alexpdp7** [comment]
Note that there might be some overlap between spellr and Vale, but in the specific case of hyphenation, Vale can check things that spellr/aspell, as far as I know, cannot.
