### ISSUE TITLE
Entry for FAQ has typo

### ISSUE THREAD

**Issue by daobrien** [StyleGuides/WritingStyleGuide#232]
FAQ
    When referring to a Frequently Asked Questions (FAQ) section of content, refer to it as "an FAQ" (to be read as "an Q") not "a FAQ." The plural form is "FAQs." 

Not sure what happened there but "an Q" is obviously wrong.

https://stylepedia.net/style/#f

**Comment by daobrien** [comment]
@julian-cable Can you address this as part of your fixes for the "F" chapter? thanks

**Comment by julian-cable** [comment]
Fixed and pushed
