### ISSUE TITLE
Capitalization of captions

### ISSUE THREAD

**Issue by julian-cable** [StyleGuides/WritingStyleGuide#236]
The Style Guide does not seem to cover the capitalization of captions specifically. It would be helpful to add explicit guidance. Recent chapter reviews have revealed considerable inconsistency of caption capitalization, so the standard might not be clear to writers.

**Comment by daobrien** [comment]
I thought this was covered in IBM. Maybe check there first and just refer to it if we need to?

**Comment by julian-cable** [comment]
I think it warrants being called out explicitly, because Red Hat capitalization guidance differs from IBM. IBM says to use sentence case generally, including for book headings, and it applies also to captions and other elements. Red Hat, on the other hand, uses headline case for headings but sentence case for captions.

**Comment by daobrien** [comment]
This is covered in 3.2 Heading Styles:
"Use sentence case for captions, legends, diagram labels, and table column headers. They are not classified as titles."

**Comment by julian-cable** [comment]
Yes, I added that paragraph in this release.
