### ISSUE TITLE
Book design issues

### ISSUE THREAD

**Issue by julian-cable** [StyleGuides/WritingStyleGuide#242]
1. Change browser tab label from "Conventions for Writers and Editors" to "Red Hat Style Guide" or similar? It would help to locate the tab more easily when many tabs are open.
2. From the stylepedia.net page, clicking the "Red Hat Style Guide" link in recent weeks didn't work for me (maybe an http versus https issue), but seems to be working now.
3. Change year 2020 > 2021 in front cover copyright statement and any other places where it occurs.
4. For the Trademarks notice on the front page, should trademarks of IBM also be included now?

**Comment by daobrien** [comment]
> 1. Change browser tab label from "Conventions for Writers and Editors" to "Red Hat Style Guide" or similar? It would help to locate the tab more easily when many tabs are open.
Part of a separate issue.

> 2. From the stylepedia.net page, clicking the "Red Hat Style Guide" link in recent weeks didn't work for me (maybe an http versus https issue), but seems to be working now.
Please raise a separate issue if this resurfaces.

> 3. Change year 2020 > 2021 in front cover copyright statement and any other places where it occurs.
This will happen when I rebuild the brand RPM.

> 4. For the Trademarks notice on the front page, should trademarks of IBM also be included now?
No. This falls under the "Red Hat is still Red Hat" heading.

**Comment by bonnevil** [comment]
@daobrien I suspect your answer to item 3 isn't true.  You probably need to change https://github.com/StyleGuides/WritingStyleGuide/blob/dev/en-US/Conventions_for_Writers_and_Editors.ent so that the `YEAR` entity is `2021`.

**Comment by daobrien** [comment]
> @daobrien I suspect your answer to item 3 isn't true. You probably need to change https://github.com/StyleGuides/WritingStyleGuide/blob/dev/en-US/Conventions_for_Writers_and_Editors.ent so that the `YEAR` entity is `2021`.

Yes, there are two places. One is in the brand and one is in the .ent file. I'll try to do both at the same time.

**Comment by daobrien** [comment]
Ok, I had that wrong. I was thinking about course books, which have the copyright year in the Preface and also in the footer (I think). No need to update the brand at this point.
