### ISSUE TITLE
Create paragraph to say that Style Guide doesn't cover use of markup

### ISSUE THREAD

**Issue by julian-cable** [StyleGuides/WritingStyleGuide#245]

**Comment by daobrien** [comment]
To help address this I'm going to remove the section `5.3. DocBook Elements` for two reasons:
1. We've all but moved away from writing in DocBook, as has the product documentation team.
2. It's not really up to us to tell others how to use DocBook. Numerous online references exist that ppl can refer to.

I'll probably add something else as well, just to say "This is about writing, not markup."
