### ISSUE TITLE
Document "standard punctuation"

### ISSUE THREAD

**Issue by daobrien** [StyleGuides/WritingStyleGuide#246]
Proposed list:
 . , : ; ' " ( ) [ ] ! ?

This is a result of the following IBM guidance:

Do not refer to an individual punctuation mark or special character by its symbol alone.
Use the name alone, or use the name followed by the symbol in parentheses.
Use the name alone if the punctuation mark or special character is **standard**, such as a comma or period, and including the symbol would clutter the text.
Include the symbol in parentheses when a punctuation mark or special character is not well known or when including the symbol improves clarity.

We just need to write a brief para about what standard punctuation marks are, why we care, and point to the IBM guide.

@julian-cable @sffrench @nmuller66

**Comment by julian-cable** [comment]
Proposed addition:

 <section id="referring">
		<title>Referring to Punctuation Marks</title>
		<para>
			To refer to a punctuation mark or special character, use its name alone if it is one of the following standard characters:
		</para>
		<para>
			. , : ; ' " ( ) [ ] ! ?
		</para>
		<para>
			For another character, use its name followed by the symbol in parentheses.  
		</para>
		<para>
			Do not use the symbol on its own.   
		</para>
		<example><title>Referring to Punctuation Marks</title>

          <para>
            Use a semicolon to separate two parts of a sentence that can each stand on their own.
          </para>
		  <para>
            The path contains the library qualifier in braces, { }.
          </para>
          </example>
		<para>
			For more details, see the <citetitle>IBM Style Guide</citetitle>.
		</para>

	</section>

**Comment by julian-cable** [comment]
Also added a section with a table of punctuation marks and special characters and their names.

**Comment by daobrien** [comment]
@julian-cable This was fully addressed in your A-Z review, yes? If so please close this. Thanks
