### ISSUE TITLE
Style Guide release notes

### ISSUE THREAD

**Issue by julian-cable** [StyleGuides/WritingStyleGuide#268]

**Comment by julian-cable** [comment]
# Red Hat Style Guide: Version 5.0 Release Notes, July 2021

Changed guide title to “Red Hat Technical Writing Style Guide”. Changed subtitle to “Style Conventions for Writers and Editors”.

Several updates, following a review of latest IBM Style Guide. Added inclusive language guidance. 

Removed guidance about DocBook and markup, to focus instead on writing. 

Deleted obsolete references, such as to diskettes and fax machines.

Minor edits so the guide itself conforms more fully with its own advice.

## Chapter 2, Grammar: 

* Added section on use of relative pronoun “that”.
* Punctuation: Added sections:
    - Exclamation Points
    - Referring to Punctuation Marks
    - Names of Punctuation Marks and Special Characters

## Chapter 3, Design:
* Clarified that sentence case is required for captions, legends, and diagram labels.
* Added subsection on phraseology for changing to the root user. 

## Chapter 4, renamed to "Choosing Appropriate Language". 
Expanded scope beyond slang and jargon, to cover the following additional topics: 
* Inclusive Language
* Phrasal Verbs (two-word verb forms)
* Avoiding Ambiguities (moved from Chapter 2 and added more categories)
* Dates and Times
Changed times of day standard from “a.m.”, “p.m.” to “AM”, “PM”.
* Numbers

## Usage A-Z: 
* Various additions and updates. Corrected alphabetical sorting sequence. 
* Moved items that are not literal term entries to an earlier chapter.
* Entries previously used a mixture of "v." and "vb." to denote a verb. Changed all occurrences to "v."
* Added entries: 
    - appendixes
    - as long as
    - blacklist
    - colocate, colocation
    - display
    - following
    - i.e.
    - indexes
    - login, log in, log in to
    - master
    - sign in, sign in to
    - slave
    - whitelist
    - wish
* Updated entries:
    - backwards-compatible
    - high-availability
    - hostname
    - OK
    - please
    - setup
    - username
    - ZIP Code
* Deleted entries:
    - e-business
    - floppy disk, floppy drive
    - IBM eServer System p
    - iSeries
    - pSeries
    - zSeries

**Comment by daobrien** [comment]
I think this is way too long and goes into too much detail for rel notes. I'd just hit the high points and provide summaries. If they're really interested they can refer to the git log for the nitty gritty.

E.g., they'll be interested in username, hostname, keyring, and the changes to the time format. Most of the other changes you could cover with summaries.

**Comment by julian-cable** [comment]
Updated shortened release notes:

# Red Hat Style Guide: Version 5.0 Release Notes, July 2021

Changed guide title to “Red Hat Technical Writing Style Guide”. Changed subtitle to “Style Conventions for Writers and Editors”.

Added inclusive language guidance. 

Added section on use of relative pronoun “that”.

Added sections on exclamation points and referring to punctuation marks. 

Clarified that sentence case is required for captions, legends, and diagram labels.

Added section on phrasal verbs (two-word verb forms).

Added more categories of ambiguities to avoid. 

Dates and Times: Changed times of day standard from “a.m.”, “p.m.” to “AM”, “PM”.

Usage A-Z added entries: appendixes, as long as, blacklist, colocate/colocation, display, following, i.e., indexes, login/log in/log in to, master, sign in/sign in to, slave, whitelist, wish

Updated entries: backwards-compatible, high-availability, hostname, lifecycle, OK, please, setup, username, ZIP Code

Removed guidance about DocBook and markup, to focus instead on writing. 

Minor edits so the guide itself conforms more fully with its own advice.

**Comment by daobrien** [comment]
Fixed
