### ISSUE TITLE
Publish release notes

### ISSUE THREAD

**Issue by julian-cable** [StyleGuides/WritingStyleGuide#287]
Make the release notes for the style guide available on stylepedia.net: 
https://github.com/StyleGuides/WritingStyleGuide/blob/dev/RELEASENOTES.md

**Comment by daobrien** [comment]
How about we do something like this, and host it on stylepedia.net, so that everything is in the same place?

[https://access.redhat.com/documentation/en-us/red_hat_ansible_automation_platform/1.2/html/red_hat_ansible_automation_platform_release_notes/index]()

@sffrench @julian-cable @nmuller66

**Comment by sffrench** [comment]
Sure, sounds good.

**Comment by julian-cable** [comment]
Looks good. Yes, I like the idea of having the release notes in the same place as the guide itself.

**Comment by daobrien** [comment]
If we use the actual `Revision_History.xml` file we'll need to patch it up a bit to fill in the gap between 2015 and 2021, otherwise it looks like it's not maintained.

The Revision should also be same as the currently published version (5.0).

**Comment by daobrien** [comment]
https://github.com/StyleGuides/ReleaseNotes

Draft is here.

**Comment by julian-cable** [comment]
@daobrien Added proposed 5.1 release notes to the `Revision_History.xml` file. I propose to reinstate this file: I would like to see the release notes included as part of the guide, and some other people have asked for that too. 

Your input would be needed for any pre-2021 release information, although I think that's low priority, as it's unlikely that anyone would want to look now at those details from that long ago.

**Comment by daobrien** [comment]
I think we sorted this out, yeah? We can include a summary diff in the SG itself that includes what's changed between the two most recent revisions, but the actual version history would be part of a separate doc.

**Comment by julian-cable** [comment]
Draft of updated release notes:
https://github.com/StyleGuides/ReleaseNotes/pull/1
