### ISSUE TITLE
'Dates' contains typo

### ISSUE THREAD

**Issue by npivic** [StyleGuides/WritingStyleGuide#290]
For dates, in line 119, there's this:

> ⁠dates
> When presenting specific dates and times numerically, see ISO Standard 8601. For dates, this means YYYMDD is the recommended representation.

I say ISO 8601 is more into `YYYY-MM-DD`. At any level, it's not YYYMDD.

**Comment by daobrien** [comment]
@npivic Can you provide more info on this? The text you quoted doesn't appear in the latest version of the style guide afaict.
Information on representing dates and times appears at https://stylepedia.net/style/5.0/#date-time

**Comment by julian-cable** [comment]
I could not find this text either. I assume that it is no longer in the latest version of the guide and that the issue can be closed?
