### ISSUE TITLE
Title case or sentence case for diagram label

### ISSUE THREAD

**Issue by herve4m** [StyleGuides/WritingStyleGuide#291]
I do not understand which case design (case vs title) I should use for diagram labels.

https://github.com/StyleGuides/WritingStyleGuide/blob/93abd0d341232d01d0e9b40b6a36b3949c72dff8/en-US/Design.xml#L19

One sentence says:

> The standard for all Red Hat technical documentation is title case for all headings and titles. Diagram labels, table headings, procedure, and formal paragraph titles all fall under this heading, and consequently, standard title case capitalization rules apply.

And the next one says:

> Use sentence case for captions, legends, diagram labels, and table column headers.

**Comment by daobrien** [comment]
Thanks @herve4m as soon as my connection is back up I'll dig in and have a look and let you know.

**Comment by daobrien** [comment]
I think I can see what's happened there. That was an addition to the last release and I think we need to clean up our terminology a bit.
I'll try to clarify with some diagrams:
"Table 2.1" is a title (not a very good one, but requires title case nonetheless). Both "Example" and "Improvement" are table column headers and require sentence case. See Table 2.7 for a better example of a correctly formatted title.
![Screenshot from 2021-10-05 10-04-10](https://user-images.githubusercontent.com/1518237/135940582-852c4916-5fa5-408c-9d1d-de4a92e81582.png)

I'm disinclined to use the term "label" at all except perhaps to identify different parts of a diagram. Refer to the following:
![Screenshot from 2021-10-05 10-13-43](https://user-images.githubusercontent.com/1518237/135941040-39c7907f-47c9-4bc6-8c8b-8bf11444a573.png)

This illustrates a screen capture with a correctly formatted title (title case) and caption (sentence case). The only labels that I would identify as such are part of the UI itself (_Applications_, _Builds_, and so on).

Does that clarify? If so, we can go ahead and update that subsection.

**Comment by daobrien** [comment]
And I've just realised that the title is not quite correct :( It should be "Navigating Menus in a Web UI".

**Comment by julian-cable** [comment]
Removed "Diagram labels" from list of title case elements.
