### ISSUE TITLE
Referring to Punctuation Marks section is inconsistent

### ISSUE THREAD

**Issue by daobrien** [StyleGuides/WritingStyleGuide#293]
https://stylepedia.net/style/5.0/#referring states that non-standard punctuation marks should be referred to by name, followed by the symbol itself in parens. Example 2.3, however, does not follow that advice.

**Comment by julian-cable** [comment]
@daobrien I think it would look awkward to enclose brackets or braces in parentheses. To work around the issue, could we add braces to the list of standard characters?
