### ISSUE TITLE
Update entry for 'unset'

### ISSUE THREAD

**Issue by daobrien** [StyleGuides/WritingStyleGuide#303]
The current entry makes no provision for the use of "unset" at all, but it is in fact correct in some cases.

unset
Incorrect. Use "Clear" instead, to refer to removing a selection from a check box.
To disable the Wobbly Widget application, clear the Enable Wobbly Widget check box.
This rule matches only TCP packets where the SYN flag is set and the ACK flag is cleared.

When referring to "clearing" environment variables and similar, accepted terminology is "unset", especially because the actual command to perform this action is `unset`.

@bonnevil @mweetman-redhat I'd appreciate your input.

https://stylepedia.net/style/5.0/#u

**Comment by mweetman-redhat** [comment]
+1 from me, 'clearing' could indicate setting a variable to null, however 'unsetting' indicates that the variable no longer exists

**Comment by julian-cable** [comment]
@daobrien How about this proposed update:
unset
Use only to refer to removing a setting for a variable. To refer instead to removing a selection from a check box, use "clear".

**Comment by mweetman-redhat** [comment]
@julian-cable  .. just a minor tweak on your last comment "Use only to refer to deleting a variable."
"Removing a setting for a variable" may be misinterpreted that the variable still exists but has no value (is null).

**Comment by daobrien** [comment]
ok, but remember that "checkbox" is one word. ;-)
Consider also the possibilities of xrefs to/from select, clear, set, and so on.

**Comment by julian-cable** [comment]
OK, we'll also need to update the "check box" entry.

**Comment by daobrien** [comment]
> OK, we'll also need to update the "check box" entry and change other references to it in the guide to one word.

Already done (but not published yet).
https://github.com/StyleGuides/WritingStyleGuide/issues/294

**Comment by julian-cable** [comment]
Added this allowed use to "unset" entry. 

Regarding xrefs: I'm not averse to the possibility of adding them, but the guide doesn't currently have entries for select, clear, and set, and not sure if we need to add them (some are already covered in IBM Style).
