### ISSUE TITLE
Update entry for 'number sign'

### ISSUE THREAD

**Issue by daobrien** [StyleGuides/WritingStyleGuide#304]
https://stylepedia.net/style/5.0/#punc-names

The entry for the number sign (#) needs to be expanded to allow for its use in (e.g.), "hash function" (see SHA-1), and probably also for the extended use covered in IBM.

**Comment by julian-cable** [comment]
@daobrien The current table entry reflects the guidance in the IBM Style "Punctuation and symbols" topic: https://www.ibm.com/docs/en/ibm-style?topic=punctuation-symbols

Do you want an entry added to the Usage Dictionary, to reflect the IBM Style "number sign" entry in Word Usage?

**Comment by daobrien** [comment]
Whatever seems appropriate? Not a hill to die on; just want to make sure that we allow for the multiple uses.

**Comment by julian-cable** [comment]
@daobrien I've added a proposed Usage Dictionary entry for "number sign".
