### ISSUE TITLE
Add guidance for "allow"

### ISSUE THREAD

**Issue by julian-cable** [StyleGuides/WritingStyleGuide#310]
Add guidance to discourage use of "allow" in an anthropomorphic context, such as "the product/feature allows the user to do xyz". Focus instead on what the user does, such as "You can use the product to ...". Use of "allow" is acceptable to refer to permissions on a system.

**Comment by daobrien** [comment]
Maybe just add as an example to https://stylepedia.net/style/#Avoiding_Slang_Metaphors-MisleadingLanguage-Anthropomorphism ?

**Comment by julian-cable** [comment]
Yes, that is a good place to add this item.

**Comment by sffrench** [comment]
LGTM
