### ISSUE TITLE
Change menu separator to greater-than character

### ISSUE THREAD

**Issue by julian-cable** [StyleGuides/WritingStyleGuide#311]
To mirror a recent change in flamel, change all style guide occurrences of an arrow character as a menu separator to a greater-than character.

**Comment by daobrien** [comment]
Not sure that I agree with this.

The Writing Style Guide does not use flamel, uses different XSL, is written in DocBook and not AsciiDoc and using a different model, and generally suffers far fewer of the issues we see in GLS content. Neither is it translated (which is where we see the misalignment and font issues in most cases). I think if we start down this path then we'll end up copying many of the other changes that flamel and adoc have used.

**Comment by julian-cable** [comment]
OK, we can drop this one then.
