### ISSUE TITLE
Avoid consecutive headings

### ISSUE THREAD

**Issue by julian-cable** [StyleGuides/WritingStyleGuide#312]
Add to the guide that a document should not contain two consecutive headings without intervening text.

**Comment by julian-cable** [comment]
Suggestion: Add the following subsection before the existing section 3.1.5:

**3.1.5. Placement of Headings**

Do not include two consecutive headings. Each heading must be followed by text. Consider whether one of the headings is unnecessary.

**Comment by daobrien** [comment]
Do you mean create that as the complete subsection?

One thing that I've noticed in our style guide is the excessive use in many places of either subsections that barely qualify (one or two sentences; see 3.3 Documenting Fonts), or that are way too deep (see ⁠3.4.6.1. Using Extended User and Group Names, which itself has further subdivisions). I'd like us to keep an eye on this sort of thing.

I agree that we should document this guideline. Does it need to be a subsection?

@nmuller66 @sffrench

**Comment by julian-cable** [comment]
I agree that it would be a short subsection. I couldn't think of a suitable existing subsection to add it.
