### ISSUE TITLE
Add guidance on nonbreaking spaces

### ISSUE THREAD

**Issue by julian-cable** [StyleGuides/WritingStyleGuide#313]
Document in the style guide the situations where two words in a product name must be kept on the same line. 

The Word Nerds meeting on 7 December agreed with David's proposal, to stipulate (only) the following scenarios: 

Red`&nbsp;`Hat Enterprise`&nbsp;`Linux`&nbsp;`8
(or similarly for any trailing version number)

Red`&nbsp;`Hat Ansible Automation`&nbsp;`Platform

Also, product names must never be broken across lines and hyphenated, such as:
Open
-Shift

**Comment by daobrien** [comment]
That wasn't my proposal. Where did you get that?

My proposal was *only* for "Red Hat" to use a `&nbsp;` (already in place), and also before the version number (also already in place). Everything else was a bit hand-wavy and nobody was really sure:

Enterprise&nbsp;Linux or not?
Automation&nbsp;Platform or not?
OpenShift&nbsp;Container&nbsp;Platform or not?

I don't think I've ever seen a product name hyphenated, but I guess it's a good idea to actually say that. We don't use the hyphenation engine; if a word doesn't fit on a line it's pushed to the next line. Other groups or departments (esp. outside Red Hat) might have different approaches, however, so stating this explicitly is probably good.

**Comment by julian-cable** [comment]
@daobrien I got it from the discussion between you and Bascha Harris in the Word Nerds chat room 10 November. Those were the items listed under your "Can we use this?" comment.

**Comment by daobrien** [comment]
ok, that was *a* proposal, yes, but this is a case of "You need to read the fine print" (don't you hate that?).

In the same thread you'll find the following:
"I feel like we got to a place where we only really paid attention to this for "Red Hat" and let other things break naturally. ALTHOUGH David pointed out that we may want to reconsider that for version numbers as we don't want them to break away from the rest of the product name. That makes sense to me, and I could see recommending adding that guidance to the entry on "version numbers."

**Comment by julian-cable** [comment]
Is there a compelling reason for not using a nonbreaking space between "Enterprise Linux", for example? This is what writers have been doing (and I have been enforcing) on our latest projects in the practice. It seems to me that, provided that we give clear guidance on the usage, the writers will follow it.

**Comment by bonnevil** [comment]
The more nonbreaking spaces you force in Red{nbsp}Hat Enterprise{nbsp}Linux{nbsp}7, for example, the more weird line breaks that you're going to have.  So if we don't need the nbsp in Enterprise Linux, I'm fine with that.

**Comment by daobrien** [comment]
> The more nonbreaking spaces you force in Red{nbsp}Hat Enterprise{nbsp}Linux{nbsp}7, for example, the more weird line breaks that you're going to have. So if we don't need the nbsp in Enterprise Linux, I'm fine with that.

Totally agree with that, plus:
- Brand/Marketing haven't been able to give us clear guidelines to work with, which is why this bug was raised to begin with.
- The simpler the rules the better.
- The more scalable the rules the better. How do you apply a rule for `Red{nbsp}Hat Enterprise{nbsp}Linux{nbsp}7` to `Red Hat Ansible Automation Platform 2.0` and so on? Our product names are getting more complex, so the simpler the rules the better IMO.

**Comment by julian-cable** [comment]
OK, I propose then to specify in the style guide to include a nonbreaking space between "Red Hat" and between "[last-word-of-product-name]" and a version number. If existing content has other nonbreaking spaces elsewhere in a product name, I would not seek to edit them out.

**Comment by julian-cable** [comment]
Proposed update to section 3.7:

Use a nonbreaking space in the following situations to avoid a break across lines: 
- In the company name, between "Red" and "Hat".
- In a product name, between the last word and a version number. 

Examples (for AsciiDoc): 
- Red{nbsp}Hat Enterprise Linux{nbsp}8
- Red{nbsp}Hat OpenShift Container Platform{nbsp}4.9

**Comment by julian-cable** [comment]
@daobrien @nmuller66 @sffrench For information and any feedback.

**Comment by sffrench** [comment]
Seems like you have it covered, LGTM Julian.

**Comment by julian-cable** [comment]
I forgot to cover one aspect. My suggested additional wording:

Do not hyphenate or break a product name across lines, as in the following incorrect example:

`Open
-Shift`
