### ISSUE TITLE
Change advice about gerunds versus imperatives in titles

### ISSUE THREAD

**Issue by julian-cable** [StyleGuides/WritingStyleGuide#318]
Update advice to show that gerunds are no longer required at the start of chapter and section titles.

**Comment by daobrien** [comment]
What's your plan here? There's currently no advice to "use gerunds" except to avoid imperative mood. I think the advice you're referring to is GLS specific.

Also remember to use labels as much as possible (to help with sorting and prioritization) and also to tag the CS editors for comments and input (where necessary).

@StyleGuides/style-guide-committers

**Comment by julian-cable** [comment]
Following a recent change of advice, I have commented out the section about using gerunds and avoiding imperative mood in titles.
