### ISSUE TITLE
Verb Phrases heading is triplicated

### ISSUE THREAD

**Issue by MackMcMacmac** [StyleGuides/WritingStyleGuide#348]
https://stylepedia.net/style/5.0/#avoiding-ambiguities

There are three headings for Verb Phrases, but I believe they should be
Infinitives
Pronouns
Verb Phrases
instead

**Comment by daobrien** [comment]
Thanks for the eagle eye. We're about to release an update and perhaps we can squeeze this in.

**Comment by julian-cable** [comment]
Good catch. I've fixed it for this release.
