### ISSUE TITLE
Cover some items from Writing Student Guides PDF?

### ISSUE THREAD

**Issue by niklucas** [StyleGuides/WritingStyleGuide#358]
I am in the process of migrating the Writing Student Guides PDF  (https://source.redhat.com/groups/public/gls-content-services/gls_content_services_folder/writing_student_guidespdf)  to either the curriculum-onboarding or curriculum-guidelines sites.

The following information *seems* like it might best fit in the Writing Style Guide. I think what needs to happen is to
1) Confirm if that is the case
2) Confirm if the rules presented are still true (the Writing Student Guides PDF is from 2020 so potentially out of date)

# Writing Course Objectives
Write course objectives for the student guide Introduction page. Write course objectives that clearly convey what the student will learn as a result of taking the whole course. State the general purpose or benefits of taking the whole course. Include an overall reference to how well a student must perform tasks or skills. Use the course description to guide you when writing course objectives.

# Writing Chapter Objectives/Goals
Write the chapter objective/goal when completing the Objectives Analysis form. Chapter objectives/goals are listed on the course wiki page under the Course Outline area and in the goal column of the introductory table. Write the chapter objective/goal after you list the section objectives (tasks) on the Objectives Analysis form, and then combine the section objectives into a sentence that focuses on the overarching, higher-level topic of the chapter. You do not need to list every task covered in a chapter when writing the chapter objective/goal. Chapter objectives/goals must start with an action verb.

# Writing Section Objectives
Create section objectives when completing the Objectives Analysis form. Insert the section title and fill out the section objectives when creating each section. Use the DCO as your guide. Section objectives describe skills the student will be able to perform after completing the section. 

Section objectives start with a verb. Section objectives include:

    • Introductory objective text: “After completing this section, you should be able to… xxx.” All section objectives start with this text.
    • Action: List the skills, knowledge, and actions students will perform in the section. Begin all section objectives with an action verb that is specific to the skill they will perform. If you have one section objective, title the section Objective and use a run-on sentence; otherwise, use a bulleted list (see following example).

Note: For sections with one (1) objective, be sure to write it as one sentence with no bullet: “After completing this section, you should be able to install Ansible Tower.”

# Writing with Verbs
Choose clear, observable, and measurable verbs in your objectives and titles to communicate to the student precisely what behavior the student should be able to demonstrate after completing the chapter or section. Ask this simple question when choosing verbs: “Can I measure or quantify “understanding” or “discovering”? The answer is no, BTW. Use the following examples to guide you:

## Effective verbs for knowledge-based sections
These verbs are specific to learning information (concepts, facts, definitions) and work well in technical content:
Explain, describe, define, list, identify…

## Effective skill-based verbs for task sections
These verbs describe a task or activity that students will do.  They clearly state what action you want students to do:
Manage, create, install, build, configure, test, connect, modify, deploy, troubleshoot,
design, validate, monitor, import, export, copy, move, add, remove, edit, delete, migrate, 
archive, download, extend, boot, reboot…

For a more complete list of knowledge-based and Skills-based verbs, visit this document. We recommend you bookmark and use it each time you write a chapter.

## Weak verbs 
Since objectives should be measurable, avoid the following words because they are not specific enough, are not measurable, and are not observable:
Understand, comprehend, appreciate, discover, conceive, learn, use, utilize, review, examine, provide, work with…

**Comment by niklucas** [comment]
@julian-cable - FYI

**Comment by daobrien** [comment]
This content is specific to GLS courses and doesn't belong in the Red Hat Writing Style Guide. @dsacco15 and Ted might have some thoughts on where this belongs.

**Comment by dsacco15** [comment]
@niklucas I agree with @daobrien. These rules are specific to our courses and would fit in the appropriate sections of **both** curriculum-onboarding and curriculum-guidelines sites. I don' think the overlap is a bad thing for new hires or seasoned associates as reminders. Before adding them, let me verify them against changes I am making currently to the Wite a Student Guide doc. I will post the final here.

**Comment by daobrien** [comment]
Assigning to @dsacco15 for now just so this doesn't get lost or forgotten.

**Comment by daobrien** [comment]
Copied to https://github.com/RedHatTraining/curriculum-guidelines/issues/159 because I can't transfer across organizations.
