### ISSUE TITLE
Hyphenation example in 3.7 needs repair

### ISSUE THREAD

**Issue by daobrien** [StyleGuides/WritingStyleGuide#364]
The example for hyphenating OpenShift in section 3.7 needs review. It's not very clear what the example is trying to demonstrate.

**Comment by julian-cable** [comment]
@daobrien The intent of the example is to show that a product name must not be broken across lines. 

What do you think would make the example better?

**Comment by daobrien** [comment]
I understand the intent but the presentation is not great. Perhaps we could deliver an actual sentence that "does the wrong thing". As well as hyphenation (and perhaps use "Red Hat Satellite Smart Management Add-On" as the example because that actually uses a hyphen, whereas "OpenShift" does not), maybe include an example of "Red Hat" breaking over lines because a non-breaking space was not used. We can highlight these errors and say "don't do this" or whatever is appropriate.

**Comment by julian-cable** [comment]
Replaced the example with a different one that incorrectly breaks over lines with the "Red Hat Satellite Smart Management Add-On" product name.
