### ISSUE TITLE
Review section 2.7.1: using a colon after "following" or "as follows" in a stem sentence

### ISSUE THREAD

**Issue by nmuller66** [StyleGuides/WritingStyleGuide#367]
Review the guidance in section 2.7. Punctuation, ⁠2.7.1. Colons and Semicolons

The guidance includes using "as follows:" or "the following:" as the stem sentence for a list, but this is counter to the IBM guidance that introductory sentences should be complete sentences; the word "following" should always precede a noun.

For clarity and ease of translation, I think the IBM guidance is preferable here. I'd like to see this guidance and example removed. 

![image](https://user-images.githubusercontent.com/50212653/167199048-a29ed504-3407-4898-8e6a-56ca9384afc7.png)

**Comment by julian-cable** [comment]
I agree that this existing example is not good. Rather than removing it, I would prefer instead to replace it with an example that is a complete sentence.

**Comment by daobrien** [comment]
What's the status of this? It's still tagged as 6.0 but not assigned to anyone. Currently no open PRs so I'm assuming 6.1?

**Comment by julian-cable** [comment]
Addressed in https://github.com/StyleGuides/WritingStyleGuide/issues/384 and https://github.com/StyleGuides/WritingStyleGuide/issues/382.
