### ISSUE TITLE
Review example in 2.7.7 Referring to Punctuation

### ISSUE THREAD

**Issue by rottndandie** [StyleGuides/WritingStyleGuide#369]
I noticed an example for this topic:

**Use a semicolon to separate two parts of a sentence that can each stand on their own.**

_Each_ has traditionally been considered singular. This should be "can each stand on its own" because _each_ breaks the plural parts into singular ones. IMO, of course. :)

**Comment by daobrien** [comment]
@julian-cable WDYT?

**Comment by julian-cable** [comment]
Agree, it should be singular.

**Comment by julian-cable** [comment]
Fixed in `jcable/6.0-fixes` branch.
