### ISSUE TITLE
Review text in 3.1.6. Unused Heading Titles

### ISSUE THREAD

**Issue by rottndandie** [StyleGuides/WritingStyleGuide#370]
Current:
This section lists various heading titles that might be used in Red Hat technical documentation, but that should be avoided except in specific circumstances.
⁠
I believe the comma before _but_ should be removed because _that_ in this context isn't the subject of the clause.

Proposed:
This section lists various heading titles that should be avoided except in specific circumstances.

**Comment by daobrien** [comment]
Fixed in 5.1
