### ISSUE TITLE
Remove extraneous comma

### ISSUE THREAD

**Issue by rottndandie** [StyleGuides/WritingStyleGuide#372]
2.4. Sentence Structure
Incorrect: A sentence is one, complete thought. 
Correct: A sentence is one complete thought. 

The adjective _one_ is in the determiner category, and _complete_ is in the qualifier category (see the Royal Order of Adjectives). 

We tech writers are nothing if not nitpicky, eh? ;)

**Comment by daobrien** [comment]
Trivial fix. Pushed straight to `dev`. Will go out in next release.
