### ISSUE TITLE
Review IBM Style updates

### ISSUE THREAD

**Issue by julian-cable** [StyleGuides/WritingStyleGuide#403]
Review updates to IBM Style (see the What's new page) since the last release of the Red Hat Style Guide, and determine any actions needed for the latter.

**Comment by daobrien** [comment]
I assume this is not going into 6.0?

**Comment by julian-cable** [comment]
Closing this issue. Monitoring IBM Style for updates is something I do periodically as standard, and would raise any issues that arise as needed. A separate issue is not needed for the monitoring activity.
