### ISSUE TITLE
Review the use of "$" as a variable marker

### ISSUE THREAD

**Issue by daobrien** [StyleGuides/WritingStyleGuide#404]
The use of "$" as a variable marker is well understood in coding circles but probably not the best choice for a style guide. See 3.1.4 and 3.1.6 for examples. We could probably replace $productname with <PRODUCT_NAME> or perhats just "PRODUCT_NAME" in a <replaceable> element.

**Comment by julian-cable** [comment]
Agree. 
I suggest to do similarly in the snippets. At least one snippet uses the $NAME syntax, which caused confusion for a writer recently.
