### ISSUE TITLE
Audience and links to other style guide

### ISSUE THREAD

**Issue by julian-cable** [StyleGuides/WritingStyleGuide#408]
Add content for the audience of this style guide, and links to other style guides as appropriate. 

Use this as a basis, and tweak as necessary:

The official style guide for Red Hat training and exam content by Global Learning Services (GLS)technical documentation, including how to write for translation, common mistakes to avoid, rules for everyday punctuation, and grammar.
Other Red Hat technical documentation, including product documentation by Customer Content Services (CCS), follows the Red Hat supplementary style guide for product documentation instead of the Red Hat Technical Writing Style Guide.

**Comment by julian-cable** [comment]
I've drafted an "Audience" section at the front of the guide to provide this information.

**Comment by julian-cable** [comment]
@daobrien I was talking with some CCS folks today, and it would definitely be good to get this content added for the 6.0 release, both in the guide itself and on the Stylepedia landing page.

**Comment by nmuller66** [comment]
@julian-cable @daobrien 
I think the proposed text is fine. It looks like there was originally a PR submitted. Is this the one that Julian rolled back because you were working on it, David?
Let's get this addition merged asap.

**Comment by nmuller66** [comment]
@julian-cable I created a branch and pushed the update to preface.xml so that the audience.xml file is included in the book. I believe this is the last critical issue to address before publishing.
