### ISSUE TITLE
Update section on using captions

### ISSUE THREAD

**Issue by daobrien** [StyleGuides/WritingStyleGuide#424]
We need to update the appropriate section to make it clear that using both
captions and callouts on figures is not supported. It doesn't work in DocBook
and requires a hack, and even though it's supported in adoc it's not good
writing practice.

We need to address the following ideas:
- This image is described in the body text. It doesn't need a caption or callouts.
- This image benefits from a caption to help illustrate what's in the body.
- This image uses callouts to describe various important parts of said image. Do
  not use a caption.

Do not use both captions and callouts on the same image.

**Comment by julian-cable** [comment]
Completed
