### ISSUE TITLE
Perform render review of 6.0 release

### ISSUE THREAD

**Issue by julian-cable** [StyleGuides/WritingStyleGuide#432]

**Comment by daobrien** [comment]
Alejandro is doing this.

**Comment by acomabon** [comment]
I can confirm that everything looks good with the `publican-brand-redhat-1.3-2` RPM

**Comment by acomabon** [comment]
Examples:

![image](https://user-images.githubusercontent.com/32303215/200796144-6a8065b2-c3a1-43c7-8d58-5fc3c4da2995.png)

![image](https://user-images.githubusercontent.com/32303215/200796186-b5df63e4-f8be-4a28-bc5a-9af28ed58286.png)

![image](https://user-images.githubusercontent.com/32303215/200796246-0df895e6-7f64-4327-8b04-517b9cf4f5c6.png)

![image](https://user-images.githubusercontent.com/32303215/200796315-00184ba9-0784-4ca9-b9a3-a1567268f0d9.png)

![image](https://user-images.githubusercontent.com/32303215/200796414-b09f2723-99dc-46ac-b7cb-62f0452e48de.png)


![image](https://user-images.githubusercontent.com/32303215/200796371-548ae213-c41a-4729-a97c-be333c195c66.png)

**Comment by daobrien** [comment]
I like it :+1: 

I'll it to Julian to close or keep open if he wants to get any more reviews done.
