### ISSUE TITLE
Add entry for Vale rule: plural.yml

### ISSUE THREAD

**Issue by daobrien** [StyleGuides/WritingStyleGuide#437]
When we create rules in Vale we need to make sure that they're based on solid guidance, and that we can refer writers to this guidance for more info.

`plural.yml` tests for "(s)" and "(es)" and provides initial guidance.

We should also ensure that these entries have IDs so that we can link directly to them in Vale rules and also in editor snippet entries.

**Comment by julian-cable** [comment]
This was one of the issues that I addressed for 6.0:
https://github.com/StyleGuides/WritingStyleGuide/issues/394

This entry is part of the section with the ID "parentheses", if that is what you are referring to.
