### ISSUE TITLE
Section on apostrophes appears to use smart quotes

### ISSUE THREAD

**Issue by daobrien** [StyleGuides/WritingStyleGuide#451]
https://stylepedia.net/style/6.0/#apostrophes

Casual inspection of this indicates the use of smart quotation marks, which we
explicitly state not to use except for direct quotations. I don't know if they
appear anywhere else.

**Comment by julian-cable** [comment]
I reviewed the Apostrophes section. All of the quotation marks in that section are straight ones. Some are included within an \<emphasis\> tag, which might explain why they resemble smart quotation marks.
