### ISSUE TITLE
Incorrect statement about admonitions

### ISSUE THREAD

**Issue by daobrien** [StyleGuides/WritingStyleGuide#455]
3.10. Using Admonitions

This section contains the following statement:

"Admonitions automatically include a suitable title according to the type of
admonition."

This is only true if you use the `publican` or `flamel` build tools and associated XSL.
We need to update this to better reflect reality.

**Comment by julian-cable** [comment]
Updated this statement:
"Depending on the tools and workflow, admonitions might automatically include a suitable title according to the type of admonition."
