### ISSUE TITLE
Use team or group instead of squad

### ISSUE THREAD

**Issue by daobrien** [StyleGuides/WritingStyleGuide#474]
IBM recommendation:
tribe noun
Do not use to refer to a group formed to accomplish a task. Use squad or squads. Tribe is a term that can be associated with colonialism or can be considered cultural appropriation.

My own and some others' reactions are that squad is immediately associated with
the military, and that either team or group would be a better choice.

**Comment by sffrench** [comment]
Agreed, squad makes me think of the military. Your suggestions of team or group are great alternatives.

**Comment by daobrien** [comment]
> Agreed, squad makes me think of the military. Your suggestions of team or group are great alternatives.

I think we could get creative with IBM's explanation and just swap a few words around to make it work.

**Comment by alexpdp7** [comment]
Note that both terms are "proper terms"; Spotify released a document that become very popular about their "tribes and squads" model, where they have very specific meanings. However, I don't think we should cite that article[^1], and actually if we are not using those terms with their definition, that would make it even more desirable to avoid using these words.

(So I'm in complete agreement, just wanted to add some background.)

[^1]: There are many people hinting online that Spotify never applied the "Spotify model".

**Comment by daobrien** [comment]
What's Spotify? :stuck_out_tongue:

**Comment by julian-cable** [comment]
Agree with using "team" or "group" instead. 
IBM decided against using the Spotify terminology, specifically "tribe". 
(IBM did not disallow "squad", but I think that term is best avoided too.)

**Comment by julian-cable** [comment]
Added entries for "tribe" and "squad" to avoid using them.
