### ISSUE TITLE
Review "Using Realistic Usernames" section

### ISSUE THREAD

**Issue by julian-cable** [StyleGuides/WritingStyleGuide#481]
Based on feedback from Fernando and others, review this section and improve its clarity:
https://stylepedia.net/style/6.0/#use-hostnames-correctly

Suggest to avoid providing "John Doe" as a suggested name. 
Specify a preferred random name generator to use.

**Comment by daobrien** [comment]
I see no reason to remove John/Jane Doe from the list of potential anonymous
names. See https://en.wikipedia.org/wiki/John_Doe

Neither do I see a need to specify a single name generator (unless there is something
actually wrong with one of the three that we provide.) If one site is down
(currently true) they still have two others to use.

**Comment by julian-cable** [comment]
Several people on the team expressed doubts about using "John Doe" for this purpose, so I removed the reference to that name as an example in this section.
