### ISSUE TITLE
Update guidance about writing titles

### ISSUE THREAD

**Issue by julian-cable** [StyleGuides/WritingStyleGuide#483]
Apply to the style guide the updated guidance that Pat announced in a department meeting on 26 April 2023:

Use a title that represents the content. 

Typically, the gerund form of a verb is a good way to title larger chunks of content such as chapters and sections. Gerunds end in "ing", such as "Troubleshooting" or "Installing".

Activities and subtasks that the student should perform can use an imperative verb for clarity. Imperative verbs are prescriptive, such as "Create" or "Delete". 

In some cases, a verb might not be appropriate because the content is purely informational. Instead of using a vague verb like "Understanding", “Describing”, “Introducing”, or “Exploring”, use a noun phrase. A noun phrase is descriptive and doesn't use a verb, for example "Installation Overview" or "The OpenShift Web Console."

When in doubt, trust your editor. Highlight the title and ask for assistance.

**Comment by daobrien** [comment]
Remember that this is a public guide aimed at a fairly wide audience, not just RHT, so you'll need to rephrase accordingly, or put some sort of qualifier in place like we've done in other RHT-specific topics. I think there's a bit about Ansible that does something like that.
