### ISSUE TITLE
Formatting Lists

### ISSUE THREAD

**Issue by julian-cable** [StyleGuides/WritingStyleGuide#490]
Add to section 5.1.1.1:

Do not use the compact option for an Outcomes list.

**Comment by daobrien** [comment]
I suspect this doesn't belong in the _Writing_ style guide because it applies specifically to RHT **Outcomes** sections. Should be in either the adoc guide or as a "hint" in the skeleton, or both.

**Comment by julian-cable** [comment]
Covered instead in https://github.com/RedHatTraining/curriculum-guidelines/pull/216 and https://github.com/RedHatTraining/scaffolding/pull/742.
