### ISSUE TITLE
Update section title for 4.8. Avoiding Ambiguities > Homographic Verbs

### ISSUE THREAD

**Issue by rclee33** [StyleGuides/WritingStyleGuide#506]
I suggest replacing the subsection title “Homographic Verbs” with a more precise title that is easier to understand and more representative of the section content. Although the term "homographic verbs" is technically correct, I think a more commonplace term for the subsection header would help surface this important guidance for writers and other content creators. Additionally, “homographic verbs” is quite a broad category, whereas the section focuses on specific verbs to avoid. Based on the section content, I suggest updating the section title to: "Avoid May and Should". (Other options: “Modal Verbs” or “Avoid Imprecise Verbs”.)

**Comment by julian-cable** [comment]
Changed the subsection title to "Avoid May and Should". 
Following this change, also reordered the subsection entries to maintain alphabetical order.
