### ISSUE TITLE
Remove references to DocBook markup

### ISSUE THREAD

**Issue by daobrien** [StyleGuides/WritingStyleGuide#516]
https://stylepedia.net/style/6.0/#view-edit-files

This section uses a couple of examples of DocBook markup. Need to make them more generic.

**Comment by julian-cable** [comment]
@daobrien Also in the same section, what does "here" documents refer to?

**Comment by daobrien** [comment]
https://tldp.org/LDP/abs/html/here-docs.html

Simple example:
```
cat << EOF
This is line 1
This is line 2
This is line 3
EOF
```
This writes 3 lines to STDOUT.
If you want (and more commonly), include `EOF > text-file` as part of the first line. That way the three lines are written to `text-file` instead.
HERE docs have a zillion uses.

**Comment by julian-cable** [comment]
Some of these references were already updated. I added some minor updates.
