### ISSUE TITLE
Add guidance about possessives with company name and product names

### ISSUE THREAD

**Issue by rclee33** [StyleGuides/WritingStyleGuide#517]
Informally, we follow the convention to avoid possessives with the company name and product names. This convention should be documented. 

The straightforward cases are product names and acronyms, where the consensus is: do not use possessives.

The company name could be a little tricky, since IBM does allow possessives with the company name when not referring to goods or services: https://www.ibm.com/docs/en/ibm-style?topic=grammar-possessives

I don’t have a strong opinion on this one; perhaps we could discuss with the larger group of editors. 

Whatever we decide, I also propose adding a section about “Possessives” (to section 2 Grammar), and add links to the new Possessives section in other relevant sections (such as 2.8.6 Apostrophes and 3.7. Using Company, Product, and Brand names correctly). In this case, keeping all guidance about possessives in one spot will make it easier to refer to and keep it updated.

**Comment by CBID2** [comment]
> Informally, we follow the convention to avoid possessives with the company name and product names. This convention should be documented.
> 
> The straightforward cases are product names and acronyms, where the consensus is: do not use possessives.
> 
> The company name could be a little tricky, since IBM does allow possessives with the company name when not referring to goods or services: https://www.ibm.com/docs/en/ibm-style?topic=grammar-possessives
> 
> I don’t have a strong opinion on this one; perhaps we could discuss with the larger group of editors.
> 
> Whatever we decide, I also propose adding a section about “Possessives” (to section 2 Grammar), and add links to the new Possessives section in other relevant sections (such as 2.8.6 Apostrophes and 3.7. Using Company, Product, and Brand names correctly). In this case, keeping all guidance about possessives in one spot will make it easier to refer to and keep it updated.

I second this @rclee33z It would be helpful to have this information in one area. Once things are settled, I would like to be assigned to this issue.

**Comment by rclee33** [comment]
@CBID2 Thanks for sharing your thoughts! Please feel free to propose an update for this issue. Also CCing @julian-cable so that he's aware of our conversation. Thank you!

**Comment by julian-cable** [comment]
@CBID2 Thank you for your offer to contribute to this issue! I would be glad for you to contribute once again. 

The main guidance to cover is as follows: 
- Do not use the possessive form to refer to product names and abbreviations. 
- (Possessives are allowed in most other situations, including to refer to people and to inanimate objects.) 
Some examples should be included. 

I am trying to find out whether it is acceptable to use a possessive with the "Red Hat" company name, where it is not part of a product name, such as "Red Hat's products and services".

We are about to release a new version of the style guide (6.1), and I am about to freeze content updates for this version. However, this is an important topic, and it would be useful to address it for this version (at least as a first iteration), if we can do so soon.

**Comment by daobrien** [comment]
> I am trying to find out whether it is acceptable to use a possessive with the "Red Hat" company name, where it is not part of a product name, such as "Red Hat's products and services".

No, we don't. Sounds very absolute, but I've yet to come across a scenario that can't be reworded to avoid it.
