### ISSUE TITLE
Improve visibility of how and where to use non-breaking spaces

### ISSUE THREAD

**Issue by daobrien** [StyleGuides/WritingStyleGuide#53]
This is not covered well (at all?). Need to make it easy for people to determine how and when to use non-breaking spaces. Maybe an entry in the Usage Dictionary or as a subsection in the Style Guide proper.
Examples:
`Red&nbsp;Hat (very RH-specific)`
`<product-name>&nbsp;<product-version>`
`<value>&nbsp;<unit>`
Other cases where splitting terms could lead to confusion, e.g., "It can use s (seconds), m (minutes), or h (hours) to describe time"

**Comment by daobrien** [comment]
Partly addressed. Still need to address <value>&nbsp;<unit>

**Comment by julian-cable** [comment]
Duplicate issue, closing it. These requirements are now met in https://github.com/StyleGuides/WritingStyleGuide/issues/572.
