### ISSUE TITLE
Capitalization in compound modifiers (in titles)

### ISSUE THREAD

**Issue by rclee33** [StyleGuides/WritingStyleGuide#530]
Our primary sources differ on whether to capitalize both terms in a compound modifier, such as in this heading title: `Exploring ROSA Cluster Air-gap Limitations and VPC Design Impacts`

titlecase.com does not capitalize `gap` in `Air-gap`, but according to IBM guidelines, both terms should be capitalized: https://www.ibm.com/docs/en/ibm-style?topic=grammar-capitalization#headline-style-capitalization

Under "Headline-style capitalization" from IBM Style:

```
This style uses initial uppercase letters for all significant words in the text. In headline-style capitalization, capitalize the initial letter of the following words:

[...]

Any word in a hyphenated compound that is not an article, preposition, or coordinating conjunction
The last word in a hyphenated compound, regardless of its part of speech
```

It seems that Red Hat courses follow the titlecase.com convention of not capitalizing both terms. If that's our style, I suggest adding this guidance to https://stylepedia.net/style/6.1/#heading-styles > Capitalization.

**Comment by daobrien** [comment]
https://stylepedia.net/style/6.1/#heading-styles

"The currently accepted reference for determining title case is at https://titlecase.com/titlecase."

It's already there. Do you think we should elaborate on that?

**Comment by daobrien** [comment]
> Oh, I thought IBM style took precedence over titlecase.com. But if the reference to titlecase.com is sufficient in this case, that works for me.

For the most part, our custom tools take precedence. Every so often we encounter something that looks off or for which we appear not to have sufficient guidance and so we have to go digging in IBM or CMOS or wherever, or maybe to Brand or Legal, depending on the issue.

Closing this issue because all seems to be in order.
