### ISSUE TITLE
Clarify that incomplete sentences in lists should not have an ending period

### ISSUE THREAD

**Issue by alexpdp7** [StyleGuides/WritingStyleGuide#531]
About https://stylepedia.net/style/6.1/#Sentence_Structure-Using_Lists_Correctly , Julian said:

> 1) add a definition of a complete sentence, and 2) show both incorrect and correct examples, rather than the correct examples only as now

See https://chat.google.com/room/AAAAzASo1xY/DC8rYDeILXE .

**Comment by julian-cable** [comment]
Also:
Add a further example that shows list items that include a verb but nevertheless are not complete sentences.
