### ISSUE TITLE
Revise guidance to use "refer to" and not "see" for references

### ISSUE THREAD

**Issue by daobrien** [StyleGuides/WritingStyleGuide#533]
From the WN thread: In the interest of inclusivity, I usually use "Refer to [site/thing]"

Although it's unlikely(?) to apply to most of our content, not everyone can see.

**Comment by julian-cable** [comment]
This is an interesting point.
I learned that IBM recently engaged an accessibility expert to evaluate whether using "see" for references might be problematic. It included a survey of several blind or visually impaired users of documentation. 
The outcome was that the majority of those users indicated that they did not have an issue with the general use of "see" in this way, and some of them even indicated that they would consider it inappropriate to try to avoid "see" just for this reason. IBM overall is retaining its guidance to use "see" for this purpose (and CCS is following suit). 

I see that in Red Hat Training, we have long used "refer to", fairly consistently. I propose updating the style guide to give this wording as the preferred usage for references.

**Comment by julian-cable** [comment]
Commenting out existing entry for "see", which said not to use "refer to" for pointing to another resource.

**Comment by daobrien** [comment]
https://stylepedia.net/style/6.1/#new

Will also need updating if we're not to contradict ourselves.

**Comment by julian-cable** [comment]
@daobrien Such an update to that section is already part of the changes addressed in https://github.com/StyleGuides/WritingStyleGuide/pull/546. I did a global find of "see" and replaced the relevant occurrences.
