### ISSUE TITLE
Clarify the use of titles and captions with tables and images

### ISSUE THREAD

**Issue by alexpdp7** [StyleGuides/WritingStyleGuide#534]
Titles use title case, while captions use sentence case.

However, it is not obvious that what we use for tables are titles; IBM calls those captions:

https://www.ibm.com/docs/en/ibm-style?topic=format-tables#captions

So if we followed that, then:

https://stylepedia.net/style/6.1/#heading-styles

Tells us that captions are sentence case, which is contrary to what we are currently doing.

I suggest we clarify that the thing we put on a table is a "title", not a caption.

**Comment by daobrien** [comment]
Might also need to review https://stylepedia.net/style/6.1/#informationlink-ratio which referes to table captions.
