### ISSUE TITLE
Clarify terms related to creating/extracting and compressing/decompressing archives

### ISSUE THREAD

**Issue by rclee33** [StyleGuides/WritingStyleGuide#549]
- Separate “tar” and “tarball” as separate entries, and clarify which form of "tar" is acceptable, and which is not.
- Add guidance to “tarball” entry.
- Add new entries for the related terms of “untar”, “unzip”, and “zip”. (I suggest including these because they are related terms to “tar” and “tarball”, and are also strictly “do not use” because they are registered trademarks. These terms came up in RH104.)

Suggested updates: 

**tar**
_n., adj._
The tape archive file format. Only use in reference to the file format, for example "a .tar file". See the Word Usage chapter of the IBM Style Guide.

_v._
Do not use to refer to the process of creating a .tar file. See the Word Usage chapter of the IBM Style Guide.

**tarball**
_n._
In most cases, do not use “tarball” to refer to a compressed archive in the tar format. Use ".tar file". 

In some limited cases, “tarball” might be introduced as a commonly used term for a compressed archive in the tar format. In such cases, briefly mentioning the term as an alternative name might be acceptable, but do not use “tarball” as the primary term to refer to compressed archives. 

**untar**
_v._
Do not use. See the Word Usage chapter of the IBM Style Guide.

**unzip**
_v._ 
Do not use. See the Word Usage chapter of the IBM Style Guide.

**zip**
_v._
Do not use. See the Word Usage chapter of the IBM Style Guide.

**Comment by rclee33** [comment]
@julian-cable @daobrien @sffrench Please share your thoughts!

**Comment by julian-cable** [comment]
@rclee33 Based on our existing word usage entries, I suggest having a single entry for "tar" and giving the guidance by parts of speech within it. In this case it would be adj./noun versus v. The term "tar" should be defined only once.

**Comment by rclee33** [comment]
@julian-cable Oh, yes -- that makes sense to me!

**Comment by rclee33** [comment]
@julian-cable I updated the original issue to address your feedback.
