### ISSUE TITLE
Update examples in section 3.4.5.2 Ansible courses (?)

### ISSUE THREAD

**Issue by rclee33** [StyleGuides/WritingStyleGuide#598]
Under "[Boolean](https://stylepedia.net/style/6.2/#b)" in the WUG, the convention is to use `true` and `false` to set Boolean values in YAML files. 

However, in section [3.4.5.2](https://stylepedia.net/style/6.2/#id2878) Ansible Courses, there are several examples showing `yes` and `no`. Are those examples out of alignment with the guidance in the WUG? Or, perhaps we need to clarify between Ansible Booleans in a playbook, and a setting in a configuration file (which might use `yes`).

**Comment by daobrien** [comment]
I think the idea there is that you can use either in playbooks, and this is just recognizing that fact. @bonnevil might have more up-to-date info on preferences.

**Comment by rclee33** [comment]
@bonnevil opened a PR to address this issue: https://github.com/StyleGuides/WritingStyleGuide/pull/600

**Comment by rclee33** [comment]
PR600 is merged, so closing this issue.
