### ISSUE TITLE
Linking to IBM Style

### ISSUE THREAD

**Issue by rclee33** [StyleGuides/WritingStyleGuide#605]
Julian and I were discussing if/when/how to link directly to IBM Style from the RHT Style Guide. I do think direct links are useful for our primary target audience in the PTL content development org. That said, it’s tricky because not everyone has access to IBM Style. (Although, there is some talk to open up IBM Style, if I recall correctly).

I like the idea to use direct links, and to add a comment about restricted access to IBM Style, such as in the RHT guide’s front matter. However, I doubt most users read the Style Guide from start to finish. Rather, my guess is that most users navigate by using the ToC and/or CTRL-F to locate the exact information they seek. Because of this behavior, I suggest also adding a concise parenthetical message about restricted access at each hyperlink to IBM Style. For example, something like “(access to the _IBM Style Guide_ is restricted)”.

Synthesizing the changes under discussion: 
- Add direct links to IBM Style (in my opinion, as often as possible, to make it easier for users to get the information that they need).
- Add a note/comment in the front matter about accessing IBM Style Guide (to provide details and context).
- Add parenthetical notes at each hyperlink (to convey important information about restricted access at the user’s point of need; if a user fails to access a link, I’m not sure that they would think to check the front matter for additional information).

Example: 
2.9.5. Quotation Marks
https://stylepedia.net/style/6.2/#quotation-marks

Current:

`Refer to the “Typographical Considerations” section in the “Quotation Marks” topic in the _IBM Style Guide_.
`

Suggested update

`Refer to the <ulink url="https://www.ibm.com/docs/en/ibm-style?topic=punctuation-quotation-marks#typographical-considerations"><citetitle>Typographical Considerations</citetitle></ulink> section in the “Quotation Marks” topic in the _IBM Style Guide_ (access to the _IBM Style Guide_ is restricted).`

Suggested update - rendered content

Refer to the [Typographical Considerations](https://www.ibm.com/docs/en/ibm-style?topic=punctuation-quotation-marks#typographical-considerations) section in the “Quotation Marks” topic in the _IBM Style Guide_ (access to the _IBM Style Guide_ is restricted).

**Comment by julian-cable** [comment]
@rclee33 I like the suggestion and the approach. I just wonder about shortening the final parenthetical text to "(access is restricted)".

**Comment by rclee33** [comment]
@julian-cable Good suggested! I like the more concise version.

**Comment by daobrien** [comment]
Just to help keep the trail, the original discussion is at https://github.com/StyleGuides/WritingStyleGuide/pull/604#discussion_r1724941221

Re "Refer to the Typographical Considerations section in the “Quotation Marks” topic in the IBM Style Guide"

tbh I think this is way too long. If you look at one or two examples, maybe not, but after a while this becomes "when do we get to the good part?"

"Refer to [Typographical Considerations](somewhere.com) in the IBM Style Guide."

And, very unfortunately, I don't think we ever found a way to include a small icon inline with text, otherwise we could just include a padlock :lock: symbol or whatever. Maybe investigate again?

**Comment by rclee33** [comment]
I like David's more concise suggestion.

I'd also be a fan of including a small lock icon to indicate restricted access, if that's possible.

**Comment by julian-cable** [comment]
I played around with the .xml source and came up with this draft:

```
Refer to <ulink url="https://www.ibm.com/docs/en/ibm-style?topic=punctuation-quotation-marks#typographical-considerations"><citetitle>Typographical Considerations</citetitle></ulink> in <citetitle>IBM Style</citetitle>
         	<guiicon><inlinemediaobject>
            <imageobject>
              <imagedata fileref="images/padlock.png"/>
            </imageobject>
          </inlinemediaobject></guiicon>.
```
which gives this result. What do you think?

![image](https://github.com/user-attachments/assets/a6f67cb2-6ffb-44ce-b5f1-7e668d0729e0)

**Comment by rclee33** [comment]
@julian-cable Thanks for creating a mockup! This looks great.
