### ISSUE TITLE
Update "infrastructure as code" to "Infrastructure as Code" (?)

### ISSUE THREAD

**Issue by rclee33** [StyleGuides/WritingStyleGuide#610]
In their Sept. 2024 meeting, Word Nerds decided to update the Corporate Style guide entry from "infrastructure as code" (no capitalization) to "Infrastructure as Code" (capital "I" and "C"). The preferred acronym will remain the same: "IaC". 

For details, the meeting agenda (https://docs.google.com/spreadsheets/d/1Go2vvHoLMT5JtrO-Z-oFJIkMZl_9QJGGYsm0o2Wgl7o/edit?gid=0#gid=0) includes some context and survey results related to this topic.

I don't recall discussing this issue before in this group -- should we follow suit? (Only if we agree that "Infrastructure as Code" is now the stronger convention.)

**Comment by daobrien** [comment]
The short/easy answer is "yes". This change, like many others, applies across all groups, not just Marketing.

Perhaps think "In _our_ Sept. 2024 meeting, WN decided..." because we are definitely part of the group; have been for years.

**Comment by rclee33** [comment]
@daobrien Ah, thanks for that clarification (that we ARE part of the Word Nerds group). I was uncertain about our status within the group.
