### ISSUE TITLE
Add file naming guidance

### ISSUE THREAD

**Issue by rclee33** [StyleGuides/WritingStyleGuide#611]
I suggest adding the file naming conventions that are described in the DocBook style guide (https://stylepedia.net/docbook/#adding-sections > File Naming Conventions) to our current style guide. 

This issue recently came up in [Slack](https://redhat-internal.slack.com/archives/C06N8F87YKZ/p1726147002993219), because our current guidance doesn't explicitly state whether dashes or underscores are preferred as term separators in file names and other names. The relevant page in Confluence is the [Replaceable Text](https://spaces.redhat.com/display/PTL/Replaceable+Text) page, where examples include project names (and similar names) that do include dashes, but this convention is not explicitly stated.

I'm opening this issue for us to discuss where to add this guidance. The (current) Style Guide makes sense to me, but it's possible that Confluence might be a better fit. (My preference is to pick one resource (and not both) to avoid having multiple sources of truth, which causes confusion and creates a maintenance burden.)

@daobrien @julian-cable @sffrench Any thoughts?

**Comment by julian-cable** [comment]
I think that Confluence would be the better place to add guidance that is specific to RH Training, or the style guide if it is for more generic uses. It seems to me that providing some RHT-specific guidance in Confluence would be the best option here.

**Comment by rclee33** [comment]
I think @daobrien agrees, and that works for me, too. I opened a ticket for that project, so we can close this one.
