### ISSUE TITLE
Update the abstract on the title page

### ISSUE THREAD

**Issue by daobrien** [StyleGuides/WritingStyleGuide#614]
Current abstract:

This guide is the official style guide for Red Hat training and certification content, and for all other technical documentation except as stated. Red Hat product documentation by Customer Content Services (CCS) follows the Red Hat supplementary style guide instead of this Red Hat Technical Writing Style Guide.

The Red Hat Technical Writing Style Guide includes everyday punctuation and grammar, common mistakes to avoid, strategies for translation and global audiences, and a word usage dictionary.

This guide is a public guide. It is reviewed and maintained by Red Hat. Contributions from the wider community are always welcomed.

A few things need review IMO:
* Red Hat training and certification content
** Make sure this reflects our current name.
* Red Hat product documentation by Customer Content Services (CCS)
** Do we need to include "by Customer Content Services (CCS)"?
* instead of this Red Hat Technical Writing Style Guide
** Just write "instead of this guide"?
* The Red Hat Technical Writing Style Guide includes everyday punctuation and grammar, common mistakes to avoid, strategies for translation and global audiences, and a word usage dictionary.
** Reword: The Red Hat Technical Writing Style Guide includes guidance for everyday punctuation and grammar, common mistakes and how to avoid them, strategies for translation and global audiences, book and writing design guidance, and a word usage dictionary. (Twiddle as necessary.)
* This guide is a public guide. It is reviewed and maintained by Red Hat. Contributions from the wider community are always welcomed.
** Rephrase: This is a public and open source guide, reviewed and maintained primarily by Red Hat. Contributions from the wider community are always welcome.
It's important to state that this is open source, and not just public. They are
two different things.

RFC

**Comment by julian-cable** [comment]
I will reword based on your suggestions. 
This content will also need to be updated on the home page of the website.
