### ISSUE TITLE
Is "can not only" acceptable?

### ISSUE THREAD

**Issue by Miciah** [StyleGuides/WritingStyleGuide#62]
⁠Chapter 11 says not to use "can not"; does this proscription apply to phrases such as "can not only" (in which "not" modifies an adverb)?

Example: "Foo can not only frob bar but can also twiddle xyzzy."

The phrase "can not only" seems fine to me though, but using "cannot" in the above example would discomfort me, so if "can not" cannot be used even in such cases, I would suggest there be a recommendation to reword the phrase entirely.

**Comment by daobrien** [comment]
Correct. In this particular example the use of "cannot" would be incorrect and clumsy. Feel free to submit a patch or recommend a rephrase, or I'll get to it as soon as I can.

Thanks for picking it up.

**Comment by daobrien** [comment]
$ git commit en-US/C.xml 
[master 241b904] Issue #62: revise entry for "cannot".
 1 file changed, 1 insertion(+), 1 deletion(-)

**Comment by daobrien** [comment]
Published.
