### ISSUE TITLE
Proposal: Add entry for "macOS"

### ISSUE THREAD

**Issue by daobrien** [StyleGuides/WritingStyleGuide#68]
" In 2016, Apple rebranded OS X to macOS, adopting the nomenclature that it uses for their other operating systems, iOS, watchOS, and tvOS. The latest version of macOS is macOS 10.12 Sierra, which was publicly released in September 2016."

From https://en.wikipedia.org/wiki/MacOS

To avoid any confusion about MacOS, macOS X, or anything else. I had to deal with this question yesterday.

**Comment by daobrien** [comment]
@sffrench or @nmuller66 One of you guys care to have a crack at this?

**Comment by sffrench** [comment]
@daobrien Do you just want a new entry for macOS and under that entry the wording above? 

" In 2016, Apple rebranded OS X to macOS, adopting the nomenclature that it uses for their other operating systems, iOS, watchOS, and tvOS. The latest version of macOS is macOS 10.12 Sierra, which was publicly released in September 2016."

**Comment by daobrien** [comment]
Yep, that'd be great, thanks.
