### ISSUE TITLE
Update entry on slang

### ISSUE THREAD

**Issue by daobrien** [StyleGuides/WritingStyleGuide#79]
From email exchange:
"...are easy to read and help ensure everyone is on the same page."
I thought this was already in our guides somewhere, but I couldn't find
it. Can we add it?

I think your example falls under this entry, as one of the things Shadowman would never say:

Avoid idioms, slang, and narrow metaphors

    Examples of idioms: apples to apples, boiling the ocean, beating a dead horse, at the end of the day, etc.
    As a rule, try to avoid these types of words and phrases. They can be unclear to some readers and don't always translate well. It's better to say exactly what you mean instead.

    Examples of metaphors: carrying the ball, drop the ball (or any other sports or ball metaphors) 
    Some cultures might not be familiar with these types of references; say exactly what you mean; e.g., "drop the ball" means to make a mistake or botch something.

**Comment by julian-cable** [comment]
Added entries to the style guide, in the `jcable/6.0-fixes` branch: 
- apples to apples
- at the end of the day
- boil the ocean
- drop the ball
- flog a dead horse
- on the same page
