### ISSUE TITLE
Update entry for he/she to include "they"

### ISSUE THREAD

**Issue by daobrien** [StyleGuides/WritingStyleGuide#84]
he, she
Do not use. Reword to avoid.

The term "they" is acceptable as a singular pronoun.

**Comment by sblasa** [comment]
@daobrien Hi! I would like to help fix this if it's still available.

**Comment by daobrien** [comment]
@sblasa No problem. Feel free to put together a short para explaining how to use "they" as a singular pronoun, and ensure we include no using gender-specific "he" or "she", etc. Create a pull request and we'll get it add. Thanks for volunteering~!

**Comment by sblasa** [comment]
@daobrien Thanks! This is my first time, so I'm still learning how to do this. I didn't see some sort of Contribute page in the repo, so I'm looking up the information, but I'm on it.

**Comment by daobrien** [comment]
Current entry is ok:

he, she
Do not use. Reword to avoid. In most cases, "they" is acceptable as a singular pronoun.

Closing.
