### ISSUE TITLE
Add entry for UUID

### ISSUE THREAD

**Issue by daobrien** [StyleGuides/WritingStyleGuide#85]
Provide a definition, correct usage, and xref to UID in the Usage Dictionary.

**Comment by daobrien** [comment]
There is an open discussion about whether or not to use UID, UUID, or just ID, and when to use upper and lower case. Need to research this a bit, bounce of internal group, etc.

**Comment by niklucas** [comment]
The statement agreed upon at the data model design meeting: 

Use ID, UID, or UUID, and the same case, as the software, command, or output requires.

**Comment by daobrien** [comment]
Ack'd, merged into devel.
